### ISSUE TITLE
Could not install on Redmi note 4g 

### ISSUE THREAD

**Issue by ghost** [manisaiprasad/MyWetherApp#1]
getting 'Parse error' while installing

**Comment by manisaiprasad** [comment]
Which Version of Android

**Comment by manisaiprasad** [comment]
try to install app which is in github
https://github.com/manisaiprasad/MyWetherApp/

**Comment by ghost** [comment]
it's 4.4

**Comment by ghost** [comment]
doesn't it support 4.4?
